name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Use Node 22.x
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'  # Specify your Node.js version
    
    - name: Install dependencies
      run: npm install
    
    - name: Ensure Format Correct
      run: npx prettier --check .
    
    - name: Ensure TS Types Correct
      run: npx tsc --noEmit
        
    - name: Run tests
      run: npm test
      working-directory: ./test
