name: Deploy Lambda Function

on:
  push:
    branches: 
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Specify your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Transpile .ts to .js
        run: tsc src/api/index.ts --lib ES2015

      # Uncomment and adjust these lines as needed
      - name: Zip Lambda Function
        run: zip -j function.zip src/api/index.js

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code \
            --function-name RestHandler \
            --zip-file fileb://function.zip
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy specific files to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
            --include 'src/api/frontend/index.html'\
            --exclude '*' \
          ./ $USER@$HOST:/var/www/html/
