name: Deploy Lambda Function

on:
  push:
    branches: 
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Specify your Node.js version

      - name: Install Dependencies
        run: |
          npm install
          npm install --prefix lambda_deploy

      - name: Transpile Frontend .ts to .js
        run: tsc src/frontend/scripts/index.ts

      - name: Compile TypeScript
        run: |
          tsc --project tsconfig.api.json
          mv lambda_deploy/node_modules/ dist/
      
      - name: Create deployment package
        run: |
          cd dist
          zip -r ../function.zip .
          cd ..

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code \
            --function-name RestHandler \
            --zip-file fileb://function.zip
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy specific files to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          # Deploy index.html to /var/www/html
          rsync -avzO --verbose -e "ssh -o StrictHostKeyChecking=no" \
            --rsync-path="sudo rsync" \
            --include 'index.html' \
            --exclude '*' \
            src/frontend/html/ $USER@$HOST:/var/www/html/

          # Deploy index.js to /var/www/scripts
          rsync -avzO --verbose -e "ssh -o StrictHostKeyChecking=no" \
            --rsync-path="sudo rsync" \
            --include 'index.js' \
            --exclude '*' \
            src/frontend/scripts/ $USER@$HOST:/var/www/html/scripts/

          # Deploy style.css to /var/www/css
          rsync -avzO --verbose -e "ssh -o StrictHostKeyChecking=no" \
            --rsync-path="sudo rsync" \
            --include 'styles.css' \
            --exclude '*' \
            src/frontend/css/ $USER@$HOST:/var/www/html/css/
