name: Deploy Lambda Function

on:
  push:
    branches: 
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Specify your Node.js version

      - name: Install Dependencies
        run: npm install

      # Uncomment and adjust these lines as needed
      # - name: Zip Lambda Function
      #   run: zip -r function.zip .  # Adjust this if you need a specific path or files

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name YOUR_LAMBDA_FUNCTION_NAME \
            --zip-file fileb://function.zip
